### ISSUE TITLE
Can't install new extensions #131

### ISSUE THREAD

**Issue by Legitti** [sirjonasxx/G-ExtensionStore#99]
I get this error, everytime I try to install something new.

I tried with the fresh install and it gives the same error, first it worked fine and I got few extensions installed but now I can'tdo anything.
I've also tried to remove Extensions folder/contents but doesn't help.

![Näyttökuva 2022-05-23 142035](https://user-images.githubusercontent.com/41343618/169822243-c67e5182-8dbb-4dd0-99e0-f5753a51ad2c.png)

**Comment by WiredSpast** [comment]
Try checking these things:

- Are you running G-Earth as admin when trying to install the extension
- Did your antivirus or firewall recently get updated, if so try setting G-Earth.exe as a trusted application

**Comment by Legitti** [comment]
Hey, yes it runs as admin by default.
And I added it to the exclusion list on Windows Defender but that didn't help.

**Comment by Legitti** [comment]
And now it wont even connect with the habbo, it finds client but gets stuck at 59% and then times out (logs out on client)

**Comment by Legitti** [comment]
I managed to solve it. Chesked the Windows defender log and it had some folder protection on by default, blocking the Java.
